name: Release Python package with pontos

on:
  pull_request:
    types: [closed]

jobs:
  build-and-release:
    name: Build and release with pontos
    # If the label 'make release' is set
    # If PR is closed because of an merge
    if: contains( github.event.pull_request.labels.*.name, 'make release') && github.event.pull_request.merged == true

    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
    - name: Build and publish
      env:
        GITHUB_USER: __token__
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        poetry run pontos-release --project ${{ github.event.repository.name }} --space ${{ github.event.repository.owner }} prepare --calendar--git-signing-key $GITHUB_TOKEN
        poetry run pontos-release --project ${{ github.event.repository.name }} --space ${{ github.event.repository.owner }} release
